In [1]:
!pip install transformers torch pandas scikit-learn


In [2]:
# import os
# import shutil
# # shutil.rmtree('./state.db')
# os.remove('./state.db')

# previous

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer

file_path = "/kaggle/input/to-add-dataset/final_final.xlsx"
p_data = pd.read_excel(file_path)
p_data=p_data[['Questions','Reference Answer',"Student's Answer","Similarity"]]

def encode(x):
    label={
        'low':0,
        'medium':1,
        'high':2
    }
    x=x.lower().strip()
    return label[x]
p_data['Similarity']=p_data['Similarity'].apply(encode)
p_data.columns=['Questions','Reference Answer','Student\'s Answer','Obtained marks']
p_data.head()

Questions  \
0  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
1  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
2  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
3  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
4  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   

                                    Reference Answer  \
0  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
1  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
2  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
3  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
4  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   

                                    Student's Answer  Obtained marks  
0  पढाईले मानिसलाई केवल केही ज्ञान मात्र जीवनमा त...               0  
1  ढाईले तर केही थाहा दिने गर्,छद जसले जीवनमा मद्...               1  
2  पढाई मानिसको सोच र ावीीजनमैशल ठूलो परिवर्तन ल्...               2  
3  पढाई केवल रप््पायत स्रोत हो, तर जीवनका समस्याह...               0  
4  पढाईले जीवनका केही पक्षहरूमा परिवर्तन ल्याउँछ।...               1

In [4]:
p_data=p_data.iloc[int(p_data.shape[0]/2):,:]
p_data.shape

(6031, 4)

# arabic

In [5]:

file_path = "/kaggle/input/arabic/to_process_arabic.xlsx"
a_data = pd.read_excel(file_path)
a_data=a_data.loc[:,['Question_E','Reference Answer_E','Student\'s Answer_E','Obtained marks']]
a_data.columns=['Questions','Reference Answer','Student\'s Answer','Obtained marks']
a_data.head()

Questions  \
0  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
1  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
2  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
3  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
4  साइबर अपराध शब्द परिभाषित गर्नुहोस्   

                                    Reference Answer  \
0  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
1  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
2  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
3  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
4  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   

                                    Student's Answer  Obtained marks  
0  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...           100.0  
1  आर्थिक प्रतिफल प्राप्त गर्ने र पीडितलाई हानि प...            60.0  
2  यो सबै इलेक्ट्रोनिक यन्त्रहरू द्वारा गरिएको अन...           100.0  
3  पीडितलाई भौतिक वा नैतिक हानि पुर्‍याउन इलेक्ट्...            52.5  
4  यो गैरकानूनी व्यवहार हो जसले इलेक्ट्रोनिक माध्...            80.0

In [6]:
def change_label(x):
    x=x/50
    if (x<=0.5):
        x=0
    elif (x>0.5 and x<=1.5):
        x=1
    elif (x>1.5 and x<=2 ):
        x=2
    return x
change_label(1.28)
a_data['Obtained marks']=a_data['Obtained marks'].apply(change_label)
a_data.head()

Questions  \
0  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
1  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
2  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
3  साइबर अपराध शब्द परिभाषित गर्नुहोस्   
4  साइबर अपराध शब्द परिभाषित गर्नुहोस्   

                                    Reference Answer  \
0  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
1  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
2  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
3  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   
4  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...   

                                    Student's Answer  Obtained marks  
0  यो सबै गैरकानूनी व्यवहार हो जुन इलेक्ट्रोनिक उ...               2  
1  आर्थिक प्रतिफल प्राप्त गर्ने र पीडितलाई हानि प...               1  
2  यो सबै इलेक्ट्रोनिक यन्त्रहरू द्वारा गरिएको अन...               2  
3  पीडितलाई भौतिक वा नैतिक हानि पुर्‍याउन इलेक्ट्...               1  
4  यो गैरकानूनी व्यवहार हो जसले इलेक्ट्रोनिक माध्...               2

# our data

In [7]:


file_path = "/kaggle/input/our-data/final 4.xlsx"
o_data = pd.read_excel(file_path)
o_data.columns=['Questions','Reference Answer','Student\'s Answer','Obtained marks']
o_data.head()

Questions  \
0  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
1  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
2  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
3  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
4  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   

                                    Reference Answer  \
0  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
1  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
2  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
3  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   
4  पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। य...   

                                    Student's Answer  Obtained marks  
0  पढाईले मानिसलाई केवल केही ज्ञान मात्र दिन्छ, त...             0.0  
1  पढाईले मानिसलाई केही थाहा दिने गर्दछ, जसले जीव...             0.0  
2  पढाई मानिसको सोच र जीवनशैलीमा ठूलो परिवर्तन ल्...             1.0  
3  पढाई केवल ज्ञानको स्रोत हो, तर जीवनका समस्याहर...             0.0  
4  पढाईले जीवनका केही पक्षहरूमा परिवर्तन ल्याउँछ।...             0.0

In [8]:
data=pd.concat([p_data,o_data,a_data])
data = data[(data['Obtained marks'] == 0) | (data['Obtained marks'] == 2)]
data.head()

Questions  \
6031  सहकारी संस्थाहरूले किसानलाई कसरी सहयोग गर्न सक...   
6032  कृषिको विकासले नेपालको समग्र समृद्धिमा कस्तो य...   
6037  कृषिको विकासले नेपालको समग्र समृद्धिमा कस्तो य...   
6038   माउन्ट एभरेष्टको उचाइ के हो र यो कहाँ अवस्थित छ?   
6041   माउन्ट एभरेष्टको उचाइ के हो र यो कहाँ अवस्थित छ?   

                                       Reference Answer  \
6031   सहकारी संस्थाहरूले किसानलाई उत्पादनका लागि सस...   
6032   कृषिको विकासले रोजगारीका अवसरहरू सिर्जना गर्छ...   
6037   कृषिको विकासले रोजगारीका अवसरहरू सिर्जना गर्छ...   
6038  माउन्ट एभरेष्टको उचाइ ८,८४८.८६ मीटर (२९,०३१.७ ...   
6041  माउन्ट एभरेष्टको उचाइ ८,८४८.८६ मीटर (२९,०३१.७ ...   

                                       Student's Answer  Obtained marks  
6031                          सहकारीले सस्तो बीउ दिन्छ।             0.0  
6032   कृषिको विकासले देशमा रोजगारी सिर्जना गर्न, उत...             2.0  
6037                                खेती राम्रो बनाउँछ।             0.0  
6038  माउन्ट एभरेष्टको उचाइ ८,८४८.८६ मीटर हो र यो ने...             2.0  
6041  माउन्ट एभरेष्ट ८,८४८ मीटर उचो छ र यो नेपाल र च...             0.0

In [9]:
import seaborn as sns

# eda

In [10]:
# from transformers import Trainer, TrainingArguments

# from transformers import AutoTokenizer, AutoModelForMaskedLM, AutoModelForSequenceClassification

# data['Questions'] = data['Questions'].astype(str)
# data['Reference Answer'] = data['Reference Answer'].astype(str)
# data["Student's Answer"] = data["Student's Answer"].astype(str)

# # Combine columns for input_text
# data['input_text'] = (
#     # "Question: " + data['Questions'] +
#     " Reference Answer: " + data['Reference Answer'] +
#     " Student Answer: " + data["Student's Answer"]
# )

# data['target'] = data['Obtained marks']

# # Split data
# train_texts, val_texts, train_labels, val_labels = train_test_split(
#     data['input_text'], data['target'], test_size=0.2, random_state=42,stratify=data['target']
# )

# # Tokenize
# tokenizer = AutoTokenizer.from_pretrained("NepBERTa/NepBERTa")
# train_encodings = tokenizer(list(train_texts), truncation=True, padding=True, max_length=512)
# val_encodings = tokenizer(list(val_texts), truncation=True, padding=True, max_length=512)


from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer

# Preprocessing: Remove data with more than 512 tokens
def filter_long_texts(texts,labels, tokenizer, max_length=512):
    # Tokenize texts and filter out those that exceed max_length
    filtered_texts = []
    filtered_labels = []
    for text, label in zip(texts, labels):
        tokenized = tokenizer(text, truncation=True, padding=False)
        if len(tokenized['input_ids']) <= max_length:  # Check if tokenized text is within the limit
            filtered_texts.append(text)
            filtered_labels.append(label)
    return filtered_texts, filtered_labels

# Preprocess data
data['Questions'] = data['Questions'].astype(str)
data['Reference Answer'] = data['Reference Answer'].astype(str)
data["Student's Answer"] = data["Student's Answer"].astype(str)

# Combine columns for input_text
data['input_text'] = (
    "Question: " + data['Questions'] +
    "Reference Answer: " + data['Reference Answer'] +
    " Student Answer: " + data["Student's Answer"]
)

data['target'] = data['Obtained marks']

# Split data
train_texts, val_texts, train_labels, val_labels = train_test_split(
    data['input_text'], data['target'], test_size=0.2, random_state=42, stratify=data['target']
)

# Initialize tokenizer
tokenizer = AutoTokenizer.from_pretrained("NepBERTa/NepBERTa")

# Remove texts that exceed max_length (512 tokens)
train_texts, train_labels = filter_long_texts(train_texts,train_labels, tokenizer, max_length=512)
val_texts, val_labels = filter_long_texts(val_texts,val_labels, tokenizer, max_length=512)

# Tokenize
train_encodings = tokenizer(list(train_texts), truncation=True, padding=True, max_length=512)
val_encodings = tokenizer(list(val_texts), truncation=True, padding=True, max_length=512)

# Optionally, check how many texts were removed
print(f"Removed {len(data['input_text']) - len(train_texts)} texts that exceeded 512 tokens.")


config.json:   0%|          | 0.00/652 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/547k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Removed 1790 texts that exceeded 512 tokens.


In [11]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

counts=data['Obtained marks'].value_counts()
print(counts)
counts=counts/counts.sum()
print(counts)
print('on dataset')
print(train_encodings[0])

Obtained marks
2.0    5340
0.0    3606
Name: count, dtype: int64
Obtained marks
2.0    0.596915
0.0    0.403085
Name: count, dtype: float64
on dataset
Encoding(num_tokens=415, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])


In [12]:
import torch

# Dataset class for PyTorch
class NepaliExamDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Create the dataset instances
train_dataset = NepaliExamDataset(train_encodings, train_labels)
val_dataset = NepaliExamDataset(val_encodings, val_labels)

# Map labels to class indices
label_mapping = {0: 0, 0.5: 1, 1: 1, 1.5: 2, 2: 2}

# Apply label mapping to training and validation datasets
train_dataset.labels = [label_mapping[label] for label in train_dataset.labels]
val_dataset.labels = [label_mapping[label] for label in val_dataset.labels]


In [13]:
#distribution after spliting
from collections import Counter

train_labels = train_dataset.labels  
label_counts = Counter(train_labels)  

test_labels = val_dataset.labels  
label_counts_test = Counter(test_labels) 

print(label_counts)
print(label_counts_test)


Counter({2: 4272, 0: 2884})
Counter({2: 1068, 0: 722})


In [14]:
from huggingface_hub import login

# Replace 'your_token_here' with your actual token
token='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'
login(token=token)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [15]:
from transformers import AutoModelForSequenceClassification,Trainer,TrainingArguments
tokenizer = AutoTokenizer.from_pretrained("NepBERTa/NepBERTa")
model = AutoModelForSequenceClassification.from_pretrained("NepBERTa/NepBERTa",from_tf=True,num_labels=3)

model.config.problem_type = "single_label_classification"
# Freeze the embeddings layer
for param in model.bert.embeddings.parameters():
    param.requires_grad = False

# Freeze the lower 6 encoder layers
for layer in model.bert.encoder.layer[:6]:
    for param in layer.parameters():
        param.requires_grad = False

# Higher layers (7-12) remain trainable
for layer in model.bert.encoder.layer[6:]:
    for param in layer.parameters():
        param.requires_grad = True

# Ensure the classifier layer is trainable
for param in model.classifier.parameters():
    param.requires_grad = True

# Check if the parameters are correctly frozen or trainable
print(model)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


tf_model.h5:   0%|          | 0.00/534M [00:00<?, ?B/s]

All TF 2.0 model weights were used when initializing BertForSequenceClassification.

All the weights of BertForSequenceClassification were initialized from the TF 2.0 model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertForSequenceClassification for predictions without further training.


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [16]:
import numpy as np
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score, 
    accuracy_score, f1_score, confusion_matrix, 
    precision_score, recall_score
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    # Convert logits to predicted class indices
    predictions = np.argmax(logits, axis=-1)

    # Compute classification metrics
    accuracy = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average="weighted")
    precision = precision_score(labels, predictions, average="weighted")
    recall = recall_score(labels, predictions, average="weighted")
    mse = mean_squared_error(labels, predictions)
    conf_matrix = confusion_matrix(labels, predictions)

    # Print the confusion matrix
    print("Confusion Matrix:\n", conf_matrix)

    return {
        "accuracy": accuracy,
        "f1": f1,
        "precision": precision,
        "recall": recall,
        "mse": mse
    }


In [17]:
# sample_text=data['Questions'][0]
# sample_text = "पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। यसबारे तपाईंको विचार दिनुहोस्।"
# tokenized=tokenizer.tokenize(sample_text)
# ids=tokenizer.convert_tokens_to_ids(tokenized)

# print(len(tokenized))
# print(ids)
# print(tokenizer.get_added_vocab())

#train on following parameters for 4-4 epoch
  # learning_rate:
  #   values: [3e-4, 1e-4, 5e-5, 3e-5]
  # per_gpu_train_batch_size:
  #   values: [8, 16, 32, 64, 128]


# Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=30,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    save_total_limit=2
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [18]:
import wandb
wandb.login(key='642cda66602a89962a6e329a891195bb114f74cf')
wandb.init(project='1', name='all added 2')

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: anidhsubedi821 (anidhsubedi821-wrc). Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [19]:
# Train the model
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[443 279]
 [118 950]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[ 469  253]
 [  60 1008]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[528 194]
 [ 77 991]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[ 453  269]
 [  33 1035]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[585 137]
 [102 966]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[603 119]
 [146 922]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[578 144]
 [120 948]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[616 106]
 [158 910]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[624  98]
 [170 898]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[557 165]
 [ 93 975]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[540 182]
 [ 92 976]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[570 152]
 [100 968]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[547 175]
 [ 89 979]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[514 208]
 [ 70 998]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[527 195]
 [ 75 993]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[547 175]
 [ 91 977]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[571 151]
 [107 961]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[547 175]
 [ 90 978]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[550 172]
 [ 94 974]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[551 171]
 [100 968]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[524 198]
 [ 76 992]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[568 154]
 [120 948]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[515 207]
 [ 80 988]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[552 170]
 [ 95 973]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[555 167]
 [101 967]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[544 178]
 [ 90 978]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[541 181]
 [ 88 980]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[549 173]
 [ 91 977]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[556 166]
 [ 93 975]]


/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


Confusion Matrix:
 [[554 168]
 [ 92 976]]


TrainOutput(global_step=13440, training_loss=0.1967967118735292, metrics={'train_runtime': 8018.3952, 'train_samples_per_second': 26.773, 'train_steps_per_second': 1.676, 'total_flos': 4.57838930369268e+16, 'train_loss': 0.1967967118735292, 'epoch': 30.0})

# for the manual evaluation

# 

In [20]:
question=""
reference_text = "पढाईले मानिसको जीवनमा ठूलो परिवर्तन ल्याउँछ। यसबारे तपाईंको विचार दिनुहोस्।"
student_text = "पढाईले मानिसको जीवनलाई सकारात्मक बनाउँछ। यसबारे तपाईंको धारणा के हो?"
inputs =  ( "Question: " + question+
    " Reference Answer: " + reference_text+
    " Student Answer: " + reference_text[:5])


model=model.to(device='cpu')
inputs = tokenizer(
    inputs,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=512
)

# Perform inference
model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
    predicted_grade = torch.argmax(logits, dim=-1).item()
    print(predicted_grade)

0
